<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<section class="py-4 border-bottom bg-light"><div class="container"><h1 class="h3 mb-1">Order <?php echo html_escape($order->order_number); ?></h1><p class="text-muted mb-0">Placed <?php echo format_datetime($order->placed_at ?: $order->created_at); ?></p></div></section>
<section class="py-5"><div class="container">
	<div class="row g-4">
		<div class="col-lg-8">
			<div class="card table-card mb-4"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Item</th><th class="text-end">Qty</th><th class="text-end">Fulfilled</th><th class="text-end">Total</th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td><?php echo html_escape($item->product_name); ?><div class="small text-muted"><?php echo html_escape($item->sku); ?></div></td><td class="text-end"><?php echo (int) $item->quantity; ?></td><td class="text-end"><?php echo (int) $item->fulfilled_quantity; ?></td><td class="text-end"><?php echo money($item->total); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
			<div class="card"><div class="card-body"><h2 class="h5">Timeline</h2><?php if (empty($timeline)): ?><p class="text-muted mb-0">No tracking updates yet.</p><?php else: foreach ($timeline as $row): ?><div class="border-bottom py-2"><div class="fw-semibold"><?php echo html_escape($row->title); ?></div><div class="small text-muted"><?php echo format_datetime($row->occurred_at); ?><?php if ($row->location): ?> · <?php echo html_escape($row->location); ?><?php endif; ?></div><?php if ($row->description): ?><div class="small"><?php echo html_escape($row->description); ?></div><?php endif; ?></div><?php endforeach; endif; ?></div></div>
		</div>
		<div class="col-lg-4">
			<div class="card mb-3"><div class="card-body"><h2 class="h5">Status</h2><div class="d-flex gap-2 mb-3"><?php echo status_badge($order->order_status, 'order'); ?><?php echo status_badge($order->payment_status, 'payment'); ?></div><div class="d-flex justify-content-between"><span>Total</span><strong><?php echo money($order->total_amount); ?></strong></div><div class="d-flex justify-content-between small text-muted"><span>Shipping</span><span><?php echo money($order->shipping_amount); ?></span></div><?php if ($order->payment_method === 'razorpay' && in_array($order->payment_status, array('pending', 'failed'), TRUE)): ?><a class="btn btn-primary btn-sm w-100 mt-3" href="<?php echo site_url('payments/razorpay/pay/'.$order->id); ?>">Pay Now</a><?php endif; ?><?php if ( ! in_array($order->order_status, array('packed', 'shipped', 'out_for_delivery', 'delivered', 'cancelled'), TRUE)): ?><hr><form method="post" action="<?php echo site_url('account/orders/cancel/'.$order->id); ?>"><input type="hidden" name="<?php echo html_escape($this->security->get_csrf_token_name()); ?>" value="<?php echo html_escape($this->security->get_csrf_hash()); ?>"><input class="form-control form-control-sm mb-2" name="reason" placeholder="Cancellation reason"><button class="btn btn-outline-danger btn-sm w-100" type="submit">Cancel Order</button></form><?php endif; ?></div></div>
			<div class="card mb-3"><div class="card-body"><h2 class="h5">Shipments</h2><?php if (empty($shipments)): ?><p class="text-muted mb-0">Shipment details appear once packed.</p><?php else: foreach ($shipments as $shipment): ?><div class="border-bottom py-2"><div class="fw-semibold"><?php echo html_escape($shipment->shipment_number); ?></div><div><?php echo status_badge($shipment->shipment_status, 'shipment'); ?></div><div class="small text-muted"><?php echo html_escape($shipment->courier_name ?: 'Courier pending'); ?> · <?php echo html_escape($shipment->tracking_number ?: 'Tracking pending'); ?></div><?php if ($shipment->tracking_url): ?><a class="small" target="_blank" rel="noopener" href="<?php echo html_escape($shipment->tracking_url); ?>">Open courier tracking</a><?php endif; ?></div><?php endforeach; endif; ?><?php if ($order->order_status === 'delivered'): ?><a class="btn btn-outline-primary btn-sm w-100 mt-3" href="<?php echo site_url('account/returns/request/'.$order->id); ?>">Request Return / Exchange</a><?php endif; ?><?php if ( ! empty($returns)): ?><hr><h3 class="h6">Return Requests</h3><?php foreach ($returns as $return): ?><div class="d-flex justify-content-between border-bottom py-2"><span><?php echo html_escape($return->return_number); ?></span><?php echo status_badge($return->return_status, 'return'); ?></div><?php endforeach; endif; ?></div></div>
			<div class="card"><div class="card-body"><h2 class="h5">Invoices</h2><?php if (empty($invoices)): ?><p class="text-muted mb-0">Invoice will appear after admin generation.</p><?php else: foreach ($invoices as $invoice): ?><a class="d-block border-bottom py-2" target="_blank" href="<?php echo site_url('account/invoices/'.$invoice->id); ?>"><?php echo html_escape($invoice->invoice_number); ?></a><?php endforeach; endif; ?></div></div>
		</div>
	</div>
</div></section>
