<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<?php echo page_header($page_title, 'Complete the fields below and save the record.', array(array('label' => 'Back', 'url' => site_url('admin/'.$resource_key), 'icon' => 'fa-arrow-left', 'class' => 'btn-outline-secondary'))); ?>
<?php if ($errors): ?><div class="alert alert-danger"><?php echo $errors; ?></div><?php endif; ?>
<form method="post" class="card" enctype="multipart/form-data" data-validate>
	<input type="hidden" name="<?php echo html_escape($this->security->get_csrf_token_name()); ?>" value="<?php echo html_escape($this->security->get_csrf_hash()); ?>">
	<div class="card-body"><div class="row g-3">
	<?php foreach ($columns as $column): $name = $column->name; $value = $record && isset($record->{$name}) ? $record->{$name} : $this->input->post($name, TRUE); $is_long = in_array($name, array('description', 'content', 'body', 'message', 'notes', 'address', 'billing_address', 'shipping_address', 'specifications', 'schema_json', 'gateway_response'), TRUE); $is_status = $name === 'status'; $field = isset($field_options[$name]) ? $field_options[$name] : array(); ?>
		<div class="col-md-<?php echo $is_long ? '12' : '6'; ?>"><label class="form-label" for="field_<?php echo html_escape($name); ?>"><?php echo html_escape(ucwords(str_replace('_', ' ', $name))); ?></label>
		<?php if (isset($field['type']) && $field['type'] === 'boolean'): ?><input type="hidden" name="<?php echo html_escape($name); ?>" value="0"><div class="form-check form-switch pt-2"><input class="form-check-input" type="checkbox" role="switch" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>" value="1" <?php echo (string) $value === '1' ? 'checked' : ''; ?>><label class="form-check-label" for="field_<?php echo html_escape($name); ?>">Enabled</label></div>
		<?php elseif (isset($field['type']) && $field['type'] === 'image'): ?><input type="file" accept="image/*" class="form-control" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>"><?php if ($value): ?><div class="form-text">Current file: <?php echo html_escape((string) $value); ?></div><?php endif; ?>
		<?php elseif (isset($field['type']) && $field['type'] === 'relation'): ?><select class="form-select" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>"><option value="">Select <?php echo html_escape(ucwords(str_replace('_id', '', str_replace('_', ' ', $name)))); ?></option><?php foreach ((array) $field['options'] as $key => $label): ?><option value="<?php echo html_escape($key); ?>" <?php echo (string) $value === (string) $key ? 'selected' : ''; ?>><?php echo html_escape($label); ?></option><?php endforeach; ?></select>
		<?php elseif (isset($field['type']) && $field['type'] === 'select'): ?><select class="form-select" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>"><option value="">Select</option><?php foreach ((array) $field['options'] as $key => $label): ?><option value="<?php echo html_escape($key); ?>" <?php echo (string) $value === (string) $key ? 'selected' : ''; ?>><?php echo html_escape($label); ?></option><?php endforeach; ?></select>
		<?php elseif ($is_status): ?><select class="form-select" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>"><?php foreach (app_config('record_statuses', array()) as $key => $status): ?><option value="<?php echo html_escape($key); ?>" <?php echo (string) $value === (string) $key ? 'selected' : ''; ?>><?php echo html_escape($status['label']); ?></option><?php endforeach; ?></select>
		<?php elseif ($is_long): ?><textarea class="form-control" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>" rows="4"><?php echo html_escape((string) $value); ?></textarea>
		<?php elseif (strpos(strtolower($column->type), 'int') !== FALSE || strpos(strtolower($column->type), 'decimal') !== FALSE): ?><input type="number" step="<?php echo strpos(strtolower($column->type), 'decimal') !== FALSE ? '0.01' : '1'; ?>" class="form-control" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>" value="<?php echo html_escape((string) $value); ?>">
		<?php elseif (strtolower($column->type) === 'date'): ?><input type="date" class="form-control" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>" value="<?php echo html_escape((string) $value); ?>">
		<?php elseif (strpos(strtolower($column->type), 'date') !== FALSE || strpos(strtolower($column->type), 'timestamp') !== FALSE): ?><input type="datetime-local" class="form-control" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>" value="<?php echo html_escape((string) $value); ?>">
		<?php else: ?><input type="text" class="form-control" name="<?php echo html_escape($name); ?>" id="field_<?php echo html_escape($name); ?>" value="<?php echo html_escape((string) $value); ?>" maxlength="<?php echo (int) $column->max_length ?: 191; ?>">
		<?php endif; ?></div>
	<?php endforeach; ?></div></div>
	<div class="card-footer d-flex justify-content-end gap-2"><a class="btn btn-light" href="<?php echo site_url('admin/'.$resource_key); ?>">Cancel</a><button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk me-2"></i>Save</button></div>
</form>
