<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<?php echo page_header($resource['label'], 'Manage '.$resource['label'].'.', array(
	array('label' => 'Export CSV', 'url' => site_url('admin/'.$resource_key.'/export'), 'icon' => 'fa-file-csv', 'class' => 'btn-outline-secondary'),
	array('label' => 'Add '.$resource['label'], 'url' => site_url('admin/'.$resource_key.'/create'), 'icon' => 'fa-plus'),
)); ?>
<form method="get" class="card mb-3" data-filter-form>
	<div class="card-body"><div class="row g-2 align-items-end">
		<div class="col-md-6"><label class="form-label" for="resourceSearch">Search</label><input id="resourceSearch" name="q" value="<?php echo html_escape($this->input->get('q', TRUE)); ?>" class="form-control" placeholder="Search <?php echo html_escape(strtolower($resource['label'])); ?>…"></div>
		<?php if (in_array('status', array_map(function ($c) { return $c->name; }, $columns), TRUE)): ?><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All statuses</option><?php foreach (app_config('record_statuses', array()) as $key => $status): ?><option value="<?php echo html_escape($key); ?>" <?php echo $this->input->get('status', TRUE) === $key ? 'selected' : ''; ?>><?php echo html_escape($status['label']); ?></option><?php endforeach; ?></select></div><?php endif; ?>
		<div class="col-md-3"><label class="form-label">Per page</label><?php echo per_page_selector($pagination['per_page']); ?></div>
	</div></div>
</form>
<form method="post" action="<?php echo site_url('admin/'.$resource_key.'/bulk'); ?>" data-bulk-form>
	<input type="hidden" name="<?php echo html_escape($this->security->get_csrf_token_name()); ?>" value="<?php echo html_escape($this->security->get_csrf_hash()); ?>">
	<div class="card table-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th><input type="checkbox" data-bulk-select></th><?php foreach ($columns as $column): ?><th><?php echo sort_link(ucwords(str_replace('_', ' ', $column->name)), $column->name); ?></th><?php endforeach; ?><th class="text-end">Actions</th></tr></thead><tbody>
	<?php if (empty($pagination['data'])): ?><tr><td colspan="<?php echo count($columns) + 2; ?>"><?php echo empty_state('No '.$resource['label'].' found', 'Try adjusting the search or create a new record.', 'fa-inbox', array('label' => 'Create record', 'url' => site_url('admin/'.$resource_key.'/create'))); ?></td></tr>
<?php else: foreach ($pagination['data'] as $row): ?><tr><td><input type="checkbox" name="ids[]" value="<?php echo (int) $row->id; ?>" data-bulk-item></td><?php foreach ($columns as $column): ?><td><?php $value = isset($row->{$column->name}) ? $row->{$column->name} : ''; ?><?php if ($column->name === 'status'): ?><?php echo status_badge($value); ?><?php elseif ($column->name === 'shipment_status'): ?><?php echo status_badge($value, 'shipment'); ?><?php elseif ($column->name === 'return_status'): ?><?php echo status_badge($value, 'return'); ?><?php elseif (isset($display_maps[$column->name][$value])): ?><?php echo html_escape($display_maps[$column->name][$value]); ?><span class="text-muted small"> #<?php echo html_escape($value); ?></span><?php elseif (in_array($column->name, array('image', 'banner', 'logo', 'avatar', 'featured_image', 'mobile_image', 'og_image'), TRUE) && $value): ?><span class="badge text-bg-light"><i class="fa-regular fa-image me-1"></i><?php echo html_escape(mb_strimwidth((string) $value, 0, 36, '…')); ?></span><?php else: ?><?php echo html_escape(mb_strimwidth((string) $value, 0, 70, '…')); ?><?php endif; ?></td><?php endforeach; ?><td class="text-end"><?php if ($resource_key === 'products'): ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo site_url('admin/products/manage/'.$row->id); ?>" title="Manage"><i class="fa-solid fa-sliders"></i></a> <?php endif; ?><?php if ($resource_key === 'orders'): ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo site_url('admin/orders/view/'.$row->id); ?>" title="View"><i class="fa-solid fa-eye"></i></a> <?php endif; ?><?php if ($resource_key === 'shipments' || $resource_key === 'tracking'): ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo site_url('admin/tracking/view/'.($resource_key === 'tracking' ? $row->shipment_id : $row->id)); ?>" title="Track"><i class="fa-solid fa-route"></i></a> <?php endif; ?><?php if ($resource_key === 'returns'): ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo site_url('admin/returns/view/'.$row->id); ?>" title="View"><i class="fa-solid fa-eye"></i></a> <?php endif; ?><?php if ($resource_key === 'payments'): ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo site_url('admin/payments/view/'.$row->id); ?>" title="View"><i class="fa-solid fa-eye"></i></a> <?php endif; ?><?php if ($resource_key === 'purchases'): ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo site_url('admin/purchases/view/'.$row->id); ?>" title="Receive"><i class="fa-solid fa-box-open"></i></a> <?php endif; ?><a class="btn btn-sm btn-outline-primary" href="<?php echo site_url('admin/'.$resource_key.'/edit/'.$row->id); ?>" title="Edit"><i class="fa-solid fa-pen"></i></a> <a class="btn btn-sm btn-outline-danger" href="<?php echo site_url('admin/'.$resource_key.'/delete/'.$row->id); ?>" data-confirm="Delete this record?" title="Delete"><i class="fa-solid fa-trash"></i></a></td></tr><?php endforeach; endif; ?>
	</tbody></table></div><div class="card-footer d-flex justify-content-between align-items-center"><div class="d-flex gap-2"><select name="bulk_action" class="form-select form-select-sm"><option value="">Bulk action</option><option value="active">Mark active</option><option value="inactive">Mark inactive</option><option value="delete">Delete</option></select><button class="btn btn-sm btn-outline-secondary" type="submit">Apply</button></div><?php echo render_pagination($pagination); ?></div></div>
</form>
