<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<section class="py-4 border-bottom bg-light"><div class="container"><h1 class="h3 mb-1">Cart</h1><p class="text-muted mb-0">Review your items before checkout.</p></div></section>
<section class="py-5"><div class="container">
	<?php if (empty($items)): ?><?php echo empty_state('Your cart is empty', 'Add products from the shop to begin.', 'fa-cart-shopping', array('label' => 'Shop Now', 'url' => site_url('shop'), 'icon' => 'fa-bag-shopping')); ?>
	<?php else: ?><div class="row g-4"><div class="col-lg-8">
		<form method="post" action="<?php echo site_url('cart/update'); ?>" class="card table-card">
			<input type="hidden" name="<?php echo html_escape($this->security->get_csrf_token_name()); ?>" value="<?php echo html_escape($this->security->get_csrf_hash()); ?>">
			<div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Product</th><th class="text-end">Price</th><th class="text-end">Qty</th><th class="text-end">Total</th><th></th></tr></thead><tbody>
				<?php foreach ($items as $item): ?><tr><td><div class="d-flex gap-3 align-items-center"><img src="<?php echo upload_url($item->image_path); ?>" alt="" width="64" height="64" class="rounded border"><div><a class="fw-semibold" href="<?php echo site_url('products/'.$item->slug); ?>"><?php echo html_escape($item->name); ?></a><div class="small text-muted"><?php echo html_escape($item->brand_name ?: $item->sku); ?></div></div></div></td><td class="text-end"><?php echo money($item->unit_price); ?></td><td class="text-end"><input class="form-control form-control-sm ms-auto" style="width:90px" type="number" min="1" name="quantities[<?php echo (int) $item->id; ?>]" value="<?php echo (int) $item->quantity; ?>"></td><td class="text-end fw-semibold"><?php echo money($item->unit_price * $item->quantity); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-danger" href="<?php echo site_url('cart/remove/'.$item->id); ?>" data-confirm="Remove this item?"><i class="fa-solid fa-trash"></i></a></td></tr><?php endforeach; ?>
			</tbody></table></div><div class="card-footer text-end"><button class="btn btn-primary" type="submit">Update Cart</button></div>
		</form></div><div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5 mb-3">Summary</h2><div class="d-flex justify-content-between mb-2"><span>Subtotal</span><span><?php echo money($totals['subtotal']); ?></span></div><div class="d-flex justify-content-between mb-2"><span>Shipping</span><span><?php echo money($totals['shipping']); ?></span></div><hr><div class="d-flex justify-content-between h5"><span>Total</span><span><?php echo money($totals['total']); ?></span></div><a class="btn btn-primary w-100 mt-3" href="<?php echo site_url('checkout'); ?>">Checkout</a></div></div></div></div><?php endif; ?>
</div></section>
