<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/** Admin menu resources mapped to their schema tables. */
$config['admin_resources'] = array(
	'products' => array('table' => 'products', 'label' => 'Products', 'permission' => 'products.view'),
	'categories' => array('table' => 'categories', 'label' => 'Categories', 'permission' => 'categories.view'),
	'brands' => array('table' => 'brands', 'label' => 'Brands', 'permission' => 'brands.view'),
	'attributes' => array('table' => 'attributes', 'label' => 'Attributes', 'permission' => 'attributes.view'),
	'variants' => array('table' => 'product_variants', 'label' => 'Variants & SKUs', 'permission' => 'variants.view'),
	'attribute-values' => array('table' => 'attribute_values', 'label' => 'Attribute Values', 'permission' => 'attributes.view'),
	'tags' => array('table' => 'tags', 'label' => 'Tags', 'permission' => 'tags.view'),
	'reviews' => array('table' => 'product_reviews', 'label' => 'Reviews', 'permission' => 'reviews.view'),
	'orders' => array('table' => 'orders', 'label' => 'Orders', 'permission' => 'orders.view'),
	'shipments' => array('table' => 'shipments', 'label' => 'Shipments', 'permission' => 'shipping.view'),
	'tracking' => array('table' => 'shipment_tracking', 'label' => 'Delivery Tracking', 'permission' => 'shipping.view'),
	'returns' => array('table' => 'return_requests', 'label' => 'Return Requests', 'permission' => 'returns.view'),
	'refunds' => array('table' => 'refunds', 'label' => 'Refunds', 'permission' => 'refunds.view'),
	'cancellations' => array('table' => 'orders', 'label' => 'Cancellations', 'permission' => 'orders.view', 'fixed_filters' => array('status' => 'cancelled')),
	'invoices' => array('table' => 'invoices', 'label' => 'Invoices', 'permission' => 'invoices.view'),
	'payments' => array('table' => 'payments', 'label' => 'Transactions', 'permission' => 'payments.view'),
	'payment-logs' => array('table' => 'payment_logs', 'label' => 'Payment Logs', 'permission' => 'payments.view'),
	'coupons' => array('table' => 'coupons', 'label' => 'Coupons', 'permission' => 'coupons.view'),
	'offers' => array('table' => 'offers', 'label' => 'Offers', 'permission' => 'offers.view'),
	'inventory' => array('table' => 'inventory', 'label' => 'Stock Overview', 'permission' => 'inventory.view'),
	'warehouses' => array('table' => 'warehouses', 'label' => 'Warehouses', 'permission' => 'warehouses.view'),
	'suppliers' => array('table' => 'suppliers', 'label' => 'Suppliers', 'permission' => 'suppliers.view'),
	'purchases' => array('table' => 'purchase_orders', 'label' => 'Purchase Entries', 'permission' => 'purchases.view'),
	'customers' => array('table' => 'users', 'label' => 'Customers', 'permission' => 'customers.view', 'fixed_filters' => array('user_type' => 'customer')),
	'users' => array('table' => 'users', 'label' => 'Staff Users', 'permission' => 'users.view', 'fixed_filters' => array('user_type !=' => 'customer')),
	'roles' => array('table' => 'roles', 'label' => 'Roles', 'permission' => 'roles.view'),
	'permissions' => array('table' => 'permissions', 'label' => 'Permissions', 'permission' => 'permissions.view'),
	'pages' => array('table' => 'pages', 'label' => 'Pages', 'permission' => 'cms.view'),
	'banners' => array('table' => 'banners', 'label' => 'Banners', 'permission' => 'banners.view'),
	'blog' => array('table' => 'blog_posts', 'label' => 'Blog Posts', 'permission' => 'blog.view'),
	'testimonials' => array('table' => 'testimonials', 'label' => 'Testimonials', 'permission' => 'testimonials.view'),
	'faqs' => array('table' => 'faqs', 'label' => 'FAQs', 'permission' => 'faqs.view'),
	'contacts' => array('table' => 'contact_messages', 'label' => 'Contact Messages', 'permission' => 'contacts.view'),
	'newsletter' => array('table' => 'newsletter_subscribers', 'label' => 'Newsletter Subscribers', 'permission' => 'newsletter.view'),
	'seo' => array('table' => 'seo_meta', 'label' => 'SEO Metadata', 'permission' => 'seo.view'),
	'notifications' => array('table' => 'notifications', 'label' => 'Notifications', 'permission' => 'notifications.view'),
	'email-templates' => array('table' => 'email_templates', 'label' => 'Email Templates', 'permission' => 'templates.view'),
	'sms-templates' => array('table' => 'sms_templates', 'label' => 'SMS Templates', 'permission' => 'templates.view'),
	'settings' => array('table' => 'settings', 'label' => 'Settings', 'permission' => 'settings.view'),
	'audit-logs' => array('table' => 'audit_logs', 'label' => 'Audit Logs', 'permission' => 'audit.view'),
	'backups' => array('table' => 'backups', 'label' => 'Backups', 'permission' => 'backups.manage'),
	'tax-rates' => array('table' => 'tax_rates', 'label' => 'Tax Rates', 'permission' => 'settings.manage'),
);
